export default {
  'dev-pie-1': {
    title: 'My example pie widget',
    type: 'pie',
    filters: [
      {
        key: 'city_clicks',
        filter: [20, 308],
      },
    ],
    groupFilter: ['LAVAL', 'MONTREAL', 'MIRABEL', 'BROSSARD'],
    valueKeys: [
      {
        key: 'city_clicks',
        title: 'City clicks (mean)',
        agg: 'mean',
      },
      {
        key: 'city_impressions',
        title: 'City impressions (sum)',
        agg: 'sum',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'geo_ca_city',
    mapGroupKey: null,
    indexKey: null,
    groupKeyTitle: 'Geo ca city',
    uniqueOptions: {
      showPercentage: true,
      donut: true,
    },
    genericOptions: {
      groupByValue: false,
      showLegend: true,
      subPlots: true,
      size: 0.6,
      titlePosition: [0.5, 1],
      legendPosition: [1, 0],
      baseColor: '#f2ff00',
      showWidgetTitle: false,
    },
    dataSource: {
      type: 'Saved query',
      id: '187',
    },
  },
  'dev-pie-2': {
    title: 'Percentage widget',
    type: 'pie',
    filters: [],
    groupFilter: [],
    valueKeys: [
      {
        key: 'renters',
        title: 'Renters (mean)',
        agg: 'mean',
      },
      {
        key: 'owners',
        title: 'Owners (mean)',
        agg: 'mean',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'city',
    mapGroupKey: null,
    indexKey: null,
    groupKeyTitle: 'City',
    uniqueOptions: {
      showPercentage: true,
      donut: false,
    },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: true,
      showLegend: true,
      subPlots: true,
      size: 0.6,
      titlePosition: [0, 1],
      legendPosition: [1, 0],
      baseColor: '#366fe4',
    },
    dataSource: {
      type: 'Execution',
      id: '141',
    },
  },
  'dev-pie-3': {
    title: 'Paymi Sample 1',
    type: 'pie',
    filters: [],
    groupFilter: [],
    valueKeys: [
      {
        key: 'Dollars Rewarded',
        title: 'Dollars Rewarded (mean)',
        agg: 'mean',
      },
      {
        key: 'Number of Transactions',
        title: 'Number of Transactions (sum)',
        agg: 'sum',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'consumer_gender',
    mapGroupKey: null,
    indexKey: null,
    groupKeyTitle: 'Consumer gender',
    uniqueOptions: {
      donut: false,
      showPercentage: true,
    },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      showTooltip: true,
      showAxisTitles: true,
      showSubPlotTitles: true,
      subPlots: false,
      size: 0.8,
      titlePosition: [0, 0],
      legendPosition: [1, 0],
      legendSize: 'Small',
      baseColor: '#366fe4',
    },
    mapViewState: {
      latitude: 44.41,
      longitude: -79.23,
      zoom: 7,
    },
    dataSource: {
      type: 'Execution',
      id: '1591',
    },
    percentageMode: false,
    presetColors: [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-bar-1': {
    title: 'My example bar widget',
    type: 'bar',
    filters: [
      {
        key: 'city_clicks',
        filter: [30, 138],
      },
    ],
    groupFilter: [],
    valueKeys: [
      {
        key: 'converted_users',
        title: 'Converted users (mean)',
        agg: 'mean',
      },
      {
        key: 'city_clicks',
        title: 'City clicks (sum)',
        agg: 'sum',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'geo_ca_city',
    mapGroupKey: null,
    indexKey: null,
    groupKeyTitle: 'Geo ca city',
    uniqueOptions: {
      stacked: true,
      showTicks: true,
    },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      subPlots: false,
      size: 0.6,
      titlePosition: [0, 1],
      legendPosition: [1, 1],
      baseColor: '#366fe4',
    },
    dataSource: {
      type: 'Saved query',
      id: '187',
    },
  },
  'dev-bar-2': {
    title: 'Time/Price Widget',
    type: 'bar',
    filters: [],
    groupFilter: ['2019-08-28', '2020-08-27'],
    valueKeys: [
      {
        key: 'price',
        title: 'Price (mean)',
        agg: 'mean',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'time',
    mapGroupKey: null,
    indexKey: null,
    groupKeyTitle: 'Time',
    uniqueOptions: {
      stacked: false,
      showTicks: true,
      spline: true,
    },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      showTooltip: true,
      subPlots: true,
      size: 0.8,
      titlePosition: [0, 1],
      legendPosition: [1, 0],
      legendSize: 'Small',
      baseColor: '#366fe4',
    },
    dataSource: {
      type: 'Execution',
      id: '1458',
    },
    percentageMode: false,
    presetColors: [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
    dateAggregation: 'Hour',
  },
  'dev-line-1': {
    title: 'Another Line Widget',
    type: 'line',
    filters: [
      {
        key: 'clicks',
        filter: [117, 423],
      },
    ],
    groupFilter: [],
    valueKeys: [
      {
        key: 'clicks',
        title: 'Clicks',
      },
      {
        key: 'revenue',
        title: 'Revenue',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: false,
    groupKey: null,
    mapGroupKey: null,
    indexKey: 'impressions',
    indexKeyTitle: 'Impressions',
    uniqueOptions: {
      spline: true,
      showTicks: true,
    },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      subPlots: true,
      size: 0.8,
      titlePosition: [0, 1],
      legendPosition: [1, 0],
      baseColor: '#366fe4',
    },
    dataSource: {
      type: 'Saved query',
      id: '191',
    },
  },
  'dev-line-2': {
    title: 'My example line widget',
    type: 'line',
    filters: [],
    groupFilter: [],
    valueKeys: [
      {
        key: 'spend',
        title: 'Spend',
      },
      {
        key: 'clicks',
        title: 'Clicks',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: false,
    groupKey: null,
    mapGroupKey: null,
    indexKey: 'impressions',
    indexKeyTitle: 'Impressions',
    uniqueOptions: {
      spline: false,
      showTicks: true,
    },
    genericOptions: {
      groupByValue: false,
      showLegend: true,
      subPlots: false,
      size: 0.2,
      titlePosition: [0, 0],
      legendPosition: [1, 1],
      baseColor: '#366fe4',
      showWidgetTitle: true,
    },
    dataSource: {
      type: 'Execution',
      id: '305',
    },
  },
  'dev-scatter-1': {
    title: 'My example scatter widget',
    type: 'scatter',
    filters: [
      {
        key: 'unique_visitors',
        filter: [0, 1474],
      },
      {
        key: 'repeat_visitors',
        filter: [43, 399],
      },
    ],
    groupFilter: [],
    valueKeys: [
      {
        key: 'unique_visitors',
        title: 'Unique visitors',
      },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: false,
    groupKey: null,
    mapGroupKey: null,
    indexKey: 'repeat_visitors',
    indexKeyTitle: 'Repeat visitors',
    uniqueOptions: {
      showTicks: true,
      showLines: false,
    },
    genericOptions: {
      showWidgetTitle: true,
      groupByValue: false,
      showLegend: true,
      showTooltip: true,
      subPlots: false,
      size: 0.8,
      titlePosition: [0, 0],
      legendPosition: [1, 0.5],
      legendSize: 'Small',
      baseColor: '#366fe4',
    },
    dataSource: {
      type: 'Saved query',
      id: '217',
    },
    percentageMode: false,
    presetColors: [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
  },
  'dev-table-1': {
    title: 'table example widget',
    type: 'table',
    filters: [],
    groupFilter: [],
    valueKeys: [
      { key: 'visits', title: 'Visits (sum)', agg: 'sum' },
      { key: 'unique_visitors', title: 'Unique visitors (mean)', agg: 'mean' },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'geo_ca_fsa',
    mapGroupKey: 'geo_ca_fsa',
    indexKey: null,
    groupKeyTitle: 'Geo ca fsa',
    mapGroupKeyTitle: 'Geo ca fsa',
    uniqueOptions: { showTicks: true, spline: false },
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      showTooltip: true,
      showAxisTitles: true,
      showSubPlotTitles: true,
      subPlots: false,
      size: 0.8,
      titlePosition: [0, 0],
      legendPosition: [1, 0],
      legendSize: 'Small',
      baseColor: '#366fe4',
    },
    dataSource: { type: 'Execution', id: '913' },
    percentageMode: false,
    presetColors: [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#366fe4',
    ],
  },
  'dev-stat-1': {
    title: 'stat example widget',
    type: 'stat',
    filters: [],
    groupFilter: [],
    valueKeys: [
      { key: ' Dollars Spent ', title: ' Dollars Spent  (max)', agg: 'max' },
    ],
    mapValueKeys: [],
    formatDataFunctions: {},
    group: true,
    groupKey: 'geo_ca_fsa',
    mapGroupKey: 'geo_ca_fsa',
    indexKey: null,
    groupKeyTitle: 'Geo ca fsa',
    mapGroupKeyTitle: 'Geo ca fsa',
    uniqueOptions: {},
    genericOptions: {
      showWidgetTitle: false,
      groupByValue: false,
      showLegend: true,
      showTooltip: true,
      showAxisTitles: true,
      showSubPlotTitles: true,
      subPlots: false,
      size: 0.8,
      titlePosition: [0, 0],
      legendPosition: [1, 0],
      legendSize: 'Small',
      baseColor: '#366fe4',
    },
    dataSource: { type: 'Execution', id: '1591' },
    percentageMode: false,
    presetColors: [
      '#3232F5',
      '#07A0C3',
      '#F0C808',
      '#91F5AD',
      '#dd1c1a',
      '#463F3A',
    ],
    dateAggregation: 'Day',
  },
}
